const AzureAuthorityHosts = (
    AZURE_PUBLIC_CLOUD = "login.microsoftonline.com",
    AZURE_CHINA = "login.chinacloudapi.cn",
    AZURE_GOVERNMENT = "login.microsoftonline.us",
)

const KnownAuthorities = AzureAuthorityHosts

const DEVELOPER_SIGN_ON_CLIENT_ID = "04b07795-8ddb-461a-bbee-02f9e1bf7b46"
const AZURE_OPENAI_SCOPE = "https://cognitiveservices.azure.com/.default"

const DEFAULT_TOKEN_REFRESH_OFFSET = Dates.Second(300)
const DEFAULT_TOKEN_REFRESH_RETRY_DELAY = Dates.Second(30)
const DEFAULT_SHARED_CACHE_DIRECTORY = joinpath(homedir(), ".IdentityService")
const INSTANCE_DISCOVERY_ENDPOINT = "https://login.microsoft.com/common/discovery/instance"
const INSTANCE_DISCOVERY_API_VERSION = "1.1"
const CACHE_NON_CAE_SUFFIX = ".nocae"
const CACHE_CAE_SUFFIX = ".cae"
const AZURE_PIPELINES_OIDC_API_VERSION = "7.1"
const AZURE_PIPELINES_TROUBLESHOOTING_GUIDE = "https://aka.ms/azsdk/python/identity/azurepipelinescredential/troubleshoot"

const ENV_AZURE_CLIENT_ID = "AZURE_CLIENT_ID"
const ENV_AZURE_CLIENT_SECRET = "AZURE_CLIENT_SECRET"
const ENV_AZURE_TENANT_ID = "AZURE_TENANT_ID"
const ENV_AZURE_CLIENT_CERTIFICATE_PATH = "AZURE_CLIENT_CERTIFICATE_PATH"
const ENV_AZURE_CLIENT_CERTIFICATE_PASSWORD = "AZURE_CLIENT_CERTIFICATE_PASSWORD"
const ENV_AZURE_CLIENT_SEND_CERTIFICATE_CHAIN = "AZURE_CLIENT_SEND_CERTIFICATE_CHAIN"
const ENV_AZURE_USERNAME = "AZURE_USERNAME"
const ENV_AZURE_PASSWORD = "AZURE_PASSWORD"
const ENV_AZURE_POD_IDENTITY_AUTHORITY_HOST = "AZURE_POD_IDENTITY_AUTHORITY_HOST"
const ENV_IDENTITY_ENDPOINT = "IDENTITY_ENDPOINT"
const ENV_IDENTITY_HEADER = "IDENTITY_HEADER"
const ENV_IDENTITY_SERVER_THUMBPRINT = "IDENTITY_SERVER_THUMBPRINT"
const ENV_IMDS_ENDPOINT = "IMDS_ENDPOINT"
const ENV_MSI_ENDPOINT = "MSI_ENDPOINT"
const ENV_MSI_SECRET = "MSI_SECRET"
const ENV_AZURE_AUTHORITY_HOST = "AZURE_AUTHORITY_HOST"
const ENV_AZURE_IDENTITY_DISABLE_MULTITENANTAUTH = "AZURE_IDENTITY_DISABLE_MULTITENANTAUTH"
const ENV_AZURE_FEDERATED_TOKEN_FILE = "AZURE_FEDERATED_TOKEN_FILE"
const ENV_AZURE_TOKEN_CREDENTIALS = "AZURE_TOKEN_CREDENTIALS"
const ENV_SYSTEM_OIDCREQUESTURI = "SYSTEM_OIDCREQUESTURI"

const CLIENT_SECRET_VARS = (ENV_AZURE_CLIENT_ID, ENV_AZURE_CLIENT_SECRET, ENV_AZURE_TENANT_ID)
const CERTIFICATE_VARS = (ENV_AZURE_CLIENT_ID, ENV_AZURE_CLIENT_CERTIFICATE_PATH, ENV_AZURE_TENANT_ID)
const USERNAME_PASSWORD_VARS = (ENV_AZURE_CLIENT_ID, ENV_AZURE_USERNAME, ENV_AZURE_PASSWORD)
